apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017  #porta do serviço (mongoDB)
    targetPort: 27017  #porta que o container irá apontar (desta forma, o port definido vai apontar para o targetPort definido)
  type: ClusterIP